### ISSUE TITLE
Some KAZ images have been cropped too much by scantailor:

### ISSUE THREAD

**Issue by ejtaal** [ejtaal/aa#22]
Search for instance for "jd" and you'll see a cropped page in KAZ.

The following command produces this list of images with a non standard aspect ratio:

for i in img/kaz/_/_png; do nice convert $i -format "%[fx:w/h] %f" info: | egrep -v "^(0.5[6789]|0.6|0.6[123])"; done | tee kaz-odd-ones-out.txt
0.280584 kaz-0001.png
1.04022 kaz-0002.png
1 kaz-0003.png
1 kaz-0004.png
0.5 kaz-0005.png
1 kaz-0006.png
0.712928 kaz-0007.png
4.74684 kaz-0008.png
0.556793 kaz-1117.png
0.559701 kaz-1272.png
0.430293 kaz-1417.png
0.559284 kaz-1899.png
0.558867 kaz-1979.png
0.476796 kaz-0177.png
0.422297 kaz-0183.png
0.472292 kaz-0185.png
0.448029 kaz-2282.png
0.559701 kaz-2315.png
0.438853 kaz-2322.png
0.443787 kaz-2354.png
0.457038 kaz-2408.png
0.454545 kaz-2412.png
0.432526 kaz-2426.png
0.451807 kaz-2428.png
0.452899 kaz-2612.png
0.422535 kaz-0249.png
0.484809 kaz-0269.png
9.86842 kaz-3041.png
1.31119 kaz-3042.png
1 kaz-3043.png
1 kaz-3044.png
0.117078 kaz-3045.png
1 kaz-3046.png
0.437828 kaz-3047.png
1 kaz-3048.png

These will need to be re-generated under supervision. To be done late iA.

**Comment by AsimIqbal2nd** [comment]
I think the images have been cropped by uniform rule, the image sizes for these cropped images are larger, you have to generate all images in same size or very similar size and then run scan-tailor again, or upload all images again after resizing the larger images to smaller image size or smaller images to larger image size.

**Comment by ejtaal** [comment]
scantailor got mixed up due to the page edge touching the text columns...Fixed by first adding a white border to the image. Weird but it works.
