### ISSUE TITLE
LS remains hidden

### ISSUE THREAD

**Issue by AsimIqbal2nd** [ejtaal/aa#23]
LS is shown on 1st load, but when a root is searched which is not found in supplement , LS is hidden and then remains hidden even if later we search a root found in supplement. It has to be manually shown each time such a shift occurs. 

I suggest by default LS remains shown, as even if shown , no image is loaded, so no problem of bandwidth or image loading, simply "LL supplement, page 2 (of 86)" is written as text which is not an issue. But the page should be displayed for roots contained in the Supplement which is not being displayed currently without manually pushing show button.

**Comment by ejtaal** [comment]
No longer applicable to the new version. Will remain hidden/open just like any other book now.
