### ISSUE TITLE
Using the online /aa on iPhone

### ISSUE THREAD

**Issue by iwanikhalid** [ejtaal/aa#25]
Assalamualaikum brother Erik,

I am a student of the Arabic language from Malaysia. Particularly from the online institution called Basooir.com. We love your app! 

I would like report an issue that most prolly is already in your bucket list. The /aa on web is jerky when we scroll down the page - it snaps back up to the top.

Hopefully this bug can easily be squashed when you have the time.

I am using iPhone 4s. And my friends who are using iPhone and Android have reported this issue as well.

Jazakallahu khairan kasiran!

**Comment by ejtaal** [comment]
Release imminent :)
